small improvements
digitalocean/marketplace-partners pull request #135
Opened 2021-04-01 06:58 UTC by coryschwartz

This solves two issues

1. `apt-get upgrade` does not reliably upgrade the system. I'm not really confident the incantation I have in this PR covers all cases, but it does cover what I'm trying to do right now. Currently, if you attempt to upgrade digitalocean's Ubuntu 20.04 image using simply `apt-get upgrade`, apt will prompt the user for a decision about what to do about openssh configuration. `--force-yes`, `-y` and other options are not sufficient to suppress it, so I had to pass an option that I'm going to keep the old config

2. The `dd` command is too slow, but it can be sped up substantially if you specify a block size. 4096 is a common choice since it is a typical block size.

I also erased lines that truncated lastlog and wtmp since it looked like that was already being truncated earlier in the script.

2021-04-01 07:05 UTC, coryschwartz commented
Regarding the apt-get update thing, I just noticed you have another issue with the same problem.

https://github.com/digitalocean/marketplace-partners/issues/133

2021-04-01 19:05 UTC, jgannondo commented
@coryschwartz  thanks for the PR. Someone from the team will review it shortly.

2021-04-02 16:09 UTC, pachamaltese requested changes

2021-04-02 20:24 UTC, coryschwartz commented on scripts/90-cleanup.sh
>  history -c
alright, I added that back. I was thinking that wasn't needed if you were unsetting the HISTFILE already, but of course you're right, there might be an existing bash history which should be removed.

2021-06-03 20:27 UTC, pachadotdev commented
it can be merged now

2021-06-08 18:09 UTC, merged